# This file was generated by GoReleaser. DO NOT EDIT.
cask "memsh" do
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_amd64.tar.gz"
      sha256 "8c34dfe6a93d73c9fdc4a04e786ef98d70d6013a2d1eb5c8cd3d91e98014b777"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_arm64.tar.gz"
      sha256 "cac6d30a1e9a4cb2d1795e5918ab1d0c013cf382b6e69e4c845b4508eee8c3f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_amd64.tar.gz"
      sha256 "336115ae986664ed0b9b355f830b0abeb38bff25544506206cc9a482f119258c"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_arm64.tar.gz"
      sha256 "1c7eff413994197ff03564b353f5a170e3cc986ce2a411cb5f83bc3c1f88aed1"
    end
  end

  name "memsh"
  desc "Virtual bash shell implemented in Go with in-memory filesystem"
  homepage "https://github.com/amjadjibon/memsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memsh"
  generate_completions_from_executable "memsh",
    shell_parameter_format: :cobra

  # No zap stanza required

end
