# This file was generated by GoReleaser. DO NOT EDIT.
cask "memsh" do
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_amd64.tar.gz"
      sha256 "1a5bb1018b17f9a37327ab4194b1b2745c07320cac2cd9961b86d71a70b35585"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_arm64.tar.gz"
      sha256 "0294dc77d9bff021340bb2467f9f90706cb7cd2f1849166b4fc3a6a165a82411"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_amd64.tar.gz"
      sha256 "21eb88266135743942917a9caf48bfec01e9a51582883b16f2e82a12976829c4"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_arm64.tar.gz"
      sha256 "8beeffc9677081f1bc613c1988e9cbf4602d4f9f534c9d306d00ed0612cb71d8"
    end
  end

  name "memsh"
  desc "Virtual bash shell implemented in Go with in-memory filesystem"
  homepage "https://github.com/amjadjibon/memsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memsh"
  generate_completions_from_executable "memsh",
    shell_parameter_format: :cobra

  # No zap stanza required

end
