# This file was generated by GoReleaser. DO NOT EDIT.
cask "memsh" do
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_amd64.tar.gz"
      sha256 "40ea90ce303fee9802fe83db0fa21e8cddd08e0e5b13aa3f5b7fbc9127cdda78"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_darwin_arm64.tar.gz"
      sha256 "8b9c1f96f210205e332aa479651e5c33ccf7142c4efe7d862d3810436bab54ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_amd64.tar.gz"
      sha256 "ca0278c17661f64f863f7be463d778a5bb27a8cfcaadd4e7310c508d4d080820"
    end
    on_arm do
      url "https://github.com/amjadjibon/memsh/releases/download/v#{version}/memsh_#{version}_linux_arm64.tar.gz"
      sha256 "ccf21851882883279adee6e63ee8fbcad67406b966eec859ead3b0666ff52252"
    end
  end

  name "memsh"
  desc "Virtual bash shell implemented in Go with in-memory filesystem"
  homepage "https://github.com/amjadjibon/memsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memsh"
  generate_completions_from_executable "memsh",
    shell_parameter_format: :cobra

  # No zap stanza required

end
